In [7]:
def test():
        print("test()for function")
        return
test()

test()for function


In [8]:
class demo:
    def test(self):
        print("test()for the class and method")
        return
        
obj=demo()
obj.test()

test()for the class and method


In [10]:
class demo1:
    def fact(self,n):
        #return the factorial
        return
    
p1=demo1()
p1.fact(5)#120

In [16]:
class demo1:
    def fact(self,n):
        #return the factorial
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
p1=demo1()
print(p1.fact(5))#120           

120


In [20]:
class demo2:
    def __init__(self,p1,p2):
        self.p1=p2
        self.p2=p1
    def add(self,p1,p2):
        return p1+p2
    
c1=demo2(10,20)
print(c1.add(100,200))

300


In [30]:
class person(object):
    def __init__(self,name):
        self.name=name
    def getname(self):
        return self.name
    def isemployee(self):
        return False
    
class employee(person):
    def isemployee(self):
        return True
    
emp=person("yash")
print(emp.getname(),emp.isemployee())
    
emp1=employee("yashwanth")
print(emp1.getname(),emp1.isemployee())
    

yash False
yashwanth True


In [31]:
list=[1,2,3,4]
print(list)

[1, 2, 3, 4]


In [32]:
import numpy as np
list=[1,2,3,4]
array=np.array(list)
print(array)

[1 2 3 4]


In [33]:
list=[1,2,3,4]
array=np.array(list)
print(array.shape)
print(array.dtype)

(4,)
int32


In [39]:
list=[1.65658,0,2,5,3,6,9,5]
array=np.array(list)
print(array.shape)
print(array.dtype)

(8,)
float64


In [42]:
a1=np.array([(1,2,3,),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [43]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [44]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [47]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
a3=np.array([7,8,9])
print(np.dstack((a1,a2,a3)))

[[[1 4 7]
  [2 5 8]
  [3 6 9]]]


In [51]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[1][3]=14
np.asarray(A)[3][3]=16
print(A)

[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1  1]
 [ 1  1  1 16]]


In [1]:
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [3]:
np.arange(2,20,20)
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [6]:
a1=np.array([(1,2,3),(4,5,6)])
print("slising column: ",a1[:,1])

slising column:  [2 5]


In [7]:
a1=np.array([(1,2,3),(4,5,6)])
print("row and column:",a1[:,1])

row and column: [2 5]


In [8]:
a1=np.random.normal(5,1,10)
print(a1)
print("min values=",np.min(a1))
print("max values=",np.max(a1))
print("mean values=",np.mean(a1))
print("median values=",np.median(a1))

[5.28797426 6.5315356  3.75389632 4.05161698 4.54543172 3.31946233
 4.1868473  4.89638161 5.40589634 7.06236944]
min values= 3.3194623252224598
max values= 7.062369444868706
mean values= 4.904141190097565
median values= 4.720906664396104


In [10]:
c1=np.array([1,2])
c2=np.array([4,5])
np.dot(c1,c2)

14

In [11]:
c1=np.array([(1,2),(3,4)])
c2=np.array([(3,4),(1,2)])
np.dot(c1,c2)

array([[ 5,  8],
       [13, 20]])

In [27]:
import pandas as pd
dict={"Name":["Anil","Akhil","Dinesh","Harsha","Ajay","Kranth"],
       "EmailID":["anil@gmail.com","akhil@gmail.com","dinesh@gmail.com","harsha@gmail.com","ajay@gmail.com","kran@gmail.com"],
        "MobileNumber":[999,888,777,888,777,999],
        "Address":["hyd","hyd","hyd","hyd","hyd","hyd"]}
b=pd.DataFrame(dict)
print(b)

     Name           EmailID  MobileNumber Address
0    Anil    anil@gmail.com           999     hyd
1   Akhil   akhil@gmail.com           888     hyd
2  Dinesh  dinesh@gmail.com           777     hyd
3  Harsha  harsha@gmail.com           888     hyd
4    Ajay    ajay@gmail.com           777     hyd
5  Kranth    kran@gmail.com           999     hyd
